export const GETTAST_REQUEST="GETTASK_REQUEST";
export const GETTAST_SUCCESS="GETTASK_SUCCESS";
export const GETTAST_FAILURE="GETTASK_FAILURE";

export const UPDATE_TASKS_REQUEST="UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS="UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE="UPDATE_TASKS_FAILURE";


export const ADD_SUBTASK_REQUEST="ADD_SUBTASK_REQUEST";
export const ADD_SUBTASK_SUCCESS="ADD_SUBTASK_SUCCESS";
export const ADD_SUBTASK_FAILURE="ADD_SUBTASK_FAILURE";

export const DELETE_SUBTASKS_REQUEST='DELETE_SUBTASKS_REQUEST';
export const DELETE_SUBTASKS_SUCCESS='DELETE_SUBTASKS_SUCCESS';
export const DELETE_SUBTASKS_FAILURE='DELETE_SUBTASKS_FAILURE';